### ISSUE TITLE
Music channel on Discord only accepts www.youtube.com as host name

### ISSUE THREAD

**Issue by simonthor** [digitalungdom-se/dub#4]
**Describe the bug**
music channel on discord only accepts ```www.youtube.com``` host name, not e.g. ```youtu.be```, a shorter version of the same URL. 

**To Reproduce**
1. Go to Digital Ungdom's discord server (https://discordapp.com/channels/468044152970674176)
2. Click on #music group (bottom left).
3. Enter ```$play https://youtu.be/dQw4w9WgXcQ``` in the text bar and press enter.
4. The message is deleted immediately.

**Expected behavior**
The music should be played instead of deleting the message.

**Screenshots**
https://gyazo.com/ff1ce8687001a3f7aa6b64afb8072fc5 (made by @simpmaestro on Discord)

**Possible solutions**
1. add "youtu.be" to host name check. This solution is simple but not scalable. For example, if we later would like to add a feature where it can play shortened links in general, the list of allowed links would become too long.
2. Check if link contains a video or not. This solution requires a lot more coding but is more scalable. This can for example look for special HTML tags such as <iframe> or <video> in the code of the link and play the content of these.

**Comment by kelszo** [comment]
Another common youtube host is `m.youtube.com` (for mobiles). The current pull request (#5) should be updated to support this.

**Comment by simonthor** [comment]
> 
> 
> Another common youtube host is `m.youtube.com` (for mobiles). The current pull request (#5) should be updated to support this.

Good point. I fixed this in the latest commit (see ee54a5b9a54d8a06db06460b0027629e79a118b8).
